Select * from PAYMENT where PAYMENT_ID=5;
ALTER TABLE PRODUCT DROP FOREIGN KEY fk_shop;
ALTER TABLE PRODUCT MODIFY PRICE_UPDATE TINYINT(1);

ALTER TABLE ITEMSTOPACK ADD SHOP_ID INTEGER, ADD CONSTRAINT fk_shop_itemstopack FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID) ON DELETE CASCADE;

ALTER TABLE ORDERS ADD STATE TINYINT;

ALTER TABLE ORDERS DROP USER_LONG ;

Select VARIANCE.VARIANCE_ID,VARIANCE_DESC,PRICE,PRODUCT_ID,QUANTITY from VARIANCE join PRICE on VARIANCE.VARIANCE_ID = PRICE.VARIANCE_ID 
				join QUANTITY on VARIANCE.VARIANCE_ID = QUANTITY.VARIANCE_ID WHERE QUANTITY.SHOP_ID=10001 and PRICE.SHOP_ID=10001;
	
ALTER TABLE SHOP MODIFY SHOP_LONG DOUBLE;

DELETE from ORDERS
SELECT * FROM DELIVERY
SELECT * FROM ORDERSDETAILS WHERE ORDER_ID=31;
UPDATE ORDERS SET STATE = 3 WHERE ORDER_ID>10;