/*category tables  */
DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.CATEGORY  CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.CATEGORY (
"CATEGORY_ID" INTEGER PRIMARY KEY, 
"CATEGORY_NAME" VARCHAR(200) NOT NULL,
"PARENT_CAT_ID" INTEGER,
"PRICE_UPDATE" INTEGER
);

/*Brand Table */
DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.BRAND  CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.BRAND (
"BRAND_ID" INTEGER PRIMARY KEY, 
"BRAND_NAME" VARCHAR(200) NOT NULL,
"BRAND_QR" VARCHAR(400)
);


/*Item category  */
DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEM_CATEGORY  CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEM_CATEGORY (
"ITEM_CATEGORY_ID" INTEGER PRIMARY KEY, 
"ITEM_CATEGORY_NAME" VARCHAR(200) NOT NULL,
"CATEGORY_ID" INTEGER,
"BRAND_ID" INTEGER , 
"PRICE_UPDATE" INTEGER,
FOREIGN KEY (CATEGORY_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.CATEGORY ON DELETE CASCADE,
FOREIGN KEY (BRAND_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.BRAND ON DELETE CASCADE
);

/* item table */

DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEM CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEM(
"ITEM_ID" INTEGER PRIMARY KEY, 
"ITEM_DESC" VARCHAR(400),
"ITEM_CATEGORY_ID" INTEGER,
"ITEM_BARCODE" BIGINT,
"ITEM_PRICE" DECIMAL(10,2),
"ITEM_QUANTITY" INTEGER,
FOREIGN KEY (ITEM_CATEGORY_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEM_CATEGORY ON DELETE CASCADE
);


/* payment table */
DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.PAYMENT CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.PAYMENT(
"PAYMENT_ID" INTEGER PRIMARY KEY, 
"PAYMENT_AMOUNT" DECIMAL(10,2),
"MODE" INTEGER,
"REFNO" VARCHAR(30)
);

DROP SEQUENCE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.PAYMENT_SEQ;
CREATE SEQUENCE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.PAYMENT_SEQ START WITH 10000;

/* order table */
DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDERS CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDERS(
"ORDER_ID" INTEGER PRIMARY KEY, 
"USER_ID" INTEGER,
"USER_NAME" VARCHAR(30),
"PAYMENT_ID" INTEGER,
"ORDER_AMOUNT" DECIMAL(10,2), 
"ORDER_DATE" TIMESTAMP,
"STATUS" INTEGER,
"ADDRESS" VARCHAR (400),
"USER_LAT" DOUBLE, 
"USER_LONG" DOUBLE,
FOREIGN KEY (PAYMENT_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.PAYMENT
);

DROP SEQUENCE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDER_SEQ;
CREATE SEQUENCE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDER_SEQ START WITH 10000;

/* order details */
DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDERDETAILS CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDERDETAILS(
"ORDER_ID" INTEGER, 
"ITEM_ID" INTEGER,
"QUANTITY" INTEGER,
FOREIGN KEY (ITEM_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEM,
FOREIGN KEY (ORDER_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDERS ON DELETE CASCADE,
UNIQUE(ORDER_ID,ITEM_ID)
);

/* temp table to get items for shop admin */
DROP TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEMSTOPACK CASCADE;
CREATE TABLE NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEMSTOPACK(
"ORDER_ID" INTEGER, 
"ITEM_ID" INTEGER,
"QUANTITY" INTEGER,
FOREIGN KEY (ITEM_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ITEM,
FOREIGN KEY (ORDER_ID) REFERENCES NEO_2Z5IEA0SEK5XKHQXICV8GWAL1.ORDERS ON DELETE CASCADE,
UNIQUE(ORDER_ID,ITEM_ID)
);
