/*category tables  */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.CATEGORY  CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.CATEGORY (
"CATEGORY_ID" INTEGER PRIMARY KEY, 
"CATEGORY_NAME" VARCHAR(200) NOT NULL,
"PARENT_CAT_ID" INTEGER
);

/*Item category  */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM_CATEGORY  CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM_CATEGORY (
"ITEM_CATEGORY_ID" INTEGER PRIMARY KEY, 
"ITEM_CATEGORY_NAME" VARCHAR(200) NOT NULL,
"CATEGORY_ID" INTEGER,
FOREIGN KEY (CATEGORY_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.CATEGORY
);

/* item table */

DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM(
"ITEM_ID" INTEGER PRIMARY KEY, 
"ITEM_DESC" VARCHAR(400),
"ITEM_CATEGORY_ID" INTEGER,
"ITEM_BARCODE" BIGINT,
"ITEM_PRICE" DECIMAL(10,2),
FOREIGN KEY (ITEM_CATEGORY_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM_CATEGORY
);


/* payment table */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.PAYMENT CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.PAYMENT(
"PAYMENT_ID" INTEGER PRIMARY KEY, 
"PAYMENT_AMOUNT" DECIMAL(10,2), 
"PAYMENT_DATE" TIMESTAMP,
"MODE" INTEGER,
"REFNO" INTEGER
);

DROP SEQUENCE NEO_ARLN25CV5SR2AB81L5FIRA5KH.PAYMENT_SEQ;
CREATE SEQUENCE NEO_ARLN25CV5SR2AB81L5FIRA5KH.PAYMENT_SEQ START WITH 10000;

/* order table */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERS CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERS(
"ORDER_ID" INTEGER PRIMARY KEY, 
"USER_ID" INTEGER,
"PAYMENT_ID" INTEGER,
"ORDER_AMOUNT" DECIMAL(10,2), 
"ORDER_DATE" TIMESTAMP,
"STATUS" INTEGER,
FOREIGN KEY (PAYMENT_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.PAYMENT
);

DROP SEQUENCE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDER_SEQ;
CREATE SEQUENCE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDER_SEQ START WITH 10000;

/* order details */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERDETAILS CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERDETAILS(
"ORDER_ID" INTEGER, 
"ITEM_ID" INTEGER,
"PRICE" DECIMAL(10,2),
"QUANTITY" INTEGER,
FOREIGN KEY (ITEM_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM,
FOREIGN KEY (ORDER_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERS ON DELETE CASCADE,
UNIQUE(ORDER_ID,ITEM_ID)
);

/* temp table to get items for shop admin */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEMSTOPACK CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEMSTOPACK(
"ORDER_ID" INTEGER, 
"ITEM_ID" INTEGER,
"PRICE" DECIMAL(10,2),
"QUANTITY" INTEGER,
FOREIGN KEY (ITEM_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM,
FOREIGN KEY (ORDER_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERS ON DELETE CASCADE,
UNIQUE(ORDER_ID,ITEM_ID)
);
