/*category tables  */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.CATEGORY  CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.CATEGORY (
"CATEGORY_ID" INTEGER PRIMARY KEY, 
"CATEGORY_NAME" VARCHAR(50) NOT NULL
);

/* item table */

DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM(
"ITEM_ID" INTEGER PRIMARY KEY, 
"ITEM_DESC" VARCHAR(400),
"ITEM_QR" VARCHAR(400),
"ITEM_IMG" VARCHAR(400),
"CATEGORY_ID" INTEGER,
"BARCODE" INTEGER,
FOREIGN KEY (CATEGORY_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.CATEGORY
);

/* order table */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERS CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERS(
"ORDER_ID" INTEGER PRIMARY KEY, 
"USER_ID" INTEGER, 
"SHOP_ID" INTEGER, 
"ORDER_AMOUNT" INTEGER, 
"ORDER_DATE" TIMESTAMP
);

DROP SEQUENCE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDER_SEQ;
CREATE SEQUENCE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDER_SEQ START WITH 10000;

/* order details */
DROP TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERDETAILS CASCADE;
CREATE TABLE NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERDETAILS(
"ORDER_ID" INTEGER, 
"ITEM_ID" VARCHAR(400),
"PRICE" INTEGER,
"QUANTITY" INTEGER,
FOREIGN KEY (ITEM_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.ITEM,
FOREIGN KEY (ORDER_ID) REFERENCES NEO_ARLN25CV5SR2AB81L5FIRA5KH.ORDERS ON DELETE CASCADE
);
