/*category tables  */
DROP TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.CATEGORY  CASCADE;
CREATE TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.CATEGORY (
"CATEGORY_ID" INTEGER PRIMARY KEY, 
"CATEGORY_NAME" VARCHAR(200) NOT NULL
);

/* item table */

DROP TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.ITEM CASCADE;
CREATE TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.ITEM(
"ITEM_ID" INTEGER PRIMARY KEY, 
"ITEM_DESC" VARCHAR(400),
"ITEM_QR" VARCHAR(400),
"ITEM_IMG" VARCHAR(400),
"CATEGORY_ID" INTEGER,
"BARCODE" INTEGER,
FOREIGN KEY (CATEGORY_ID) REFERENCES NEO_CM69DUGNWBYHBX3IPA1OC978I.CATEGORY
);

/* order table */
DROP TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.ORDER CASCADE;
CREATE TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.ORDER(
"ORDER_ID" INTEGER PRIMARY KEY, 
"USER_ID" INTEGER, 
"SHOP_ID" INTEGER, 
"ORDER_AMOUNT" INTEGER, 
"ORDER_DATE" TIMESTAMP,
FOREIGN KEY (USER_ID) REFERENCES NEO_CM69DUGNWBYHBX3IPA1OC978I.USER ON DELETE CASCADE,
FOREIGN KEY (SHOP_ID) REFERENCES NEO_CM69DUGNWBYHBX3IPA1OC978I.SHOP ON DELETE CASCADE,
);

DROP SEQUENCE NEO_CM69DUGNWBYHBX3IPA1OC978I.ORDER_SEQ;
CREATE SEQUENCE NEO_CM69DUGNWBYHBX3IPA1OC978I.ORDER_SEQ START WITH 10000;

/* order details */
DROP TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.ORDERDETAILS CASCADE;
CREATE TABLE NEO_CM69DUGNWBYHBX3IPA1OC978I.PRICE(
"ORDER_ID" INTEGER, 
"ITEM_ID" VARCHAR(400),
"PRICE" INTEGER,
"QUANTITY" INTEGER,
FOREIGN KEY (ITEM_ID) REFERENCES NEO_CM69DUGNWBYHBX3IPA1OC978I.ITEM,
FOREIGN KEY (ORDER_ID) REFERENCES NEO_CM69DUGNWBYHBX3IPA1OC978I.ORDER ON DELETE CASCADE
);
